name: Run Aseprite 
description: Executes Aseprite on Ubuntu

inputs:
  args:
    description: CLI arguments that are passed to Aseprite
    required: true

outputs:
  exit-code:
    description: Exit code of Aseprite

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.args }}
