name: Run Sample Script

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-sample-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run sample-script.lua
        uses: ./
        id: run-sample-script
        with:
          args: '--script sample-script.lua'

      - name: Print result
        run: |
          echo "exit code: ${{ steps.run-sample-script.outputs.exit-code }}"
          echo "stdout:"
          cat stdout.txt
          echo "stderr:"
          cat stderr.txt
